---
# tasks file for Final
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=default.cfg.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: start ngnix
  service: name=nginx state=started
